-- 도서 테이블에 선수과목 책번호 칼럼 추가
ALTER TABLE BOOK ADD PREREQUISITE INT;

-- 선수과목 책번호 업데이트
UPDATE BOOK 
  SET PREREQUISITE = 222
WHERE NO = 111;

UPDATE BOOK 
  SET PREREQUISITE = 555
WHERE NO = 222;

SELECT *
  FROM BOOK;

-- 셀프 조인
SELECT A.NAME AS 강의명, B.NAME AS 선수과목
  FROM BOOK A JOIN BOOK B
    ON A.PREREQUISITE = B.NO;
