-- 1. 고양이와 개는 몇 마리 있을까
SELECT ANIMAL_TYPE, COUNT(*) AS count
FROM ANIMAL_INS
GROUP BY ANIMAL_TYPE
ORDER BY ANIMAL_TYPE;

-- 2. 동명 동물 수 찾기
-- HAVING 조건
SELECT NAME, COUNT(NAME) AS COUNT
FROM ANIMAL_INS
GROUP BY NAME
HAVING COUNT(NAME) > 1
ORDER BY NAME;

-- 3. 입양 시각 구하기
-- BETWEEN 연산자로 범위 보장
-- ALIAS로 가능하네?

-- MySQL => HOUR
SELECT 
    HOUR(DATETIME) AS HOUR, 
    COUNT(*) AS COUNT
FROM ANIMAL_OUTS
GROUP BY HOUR
HAVING HOUR BETWEEN 9 AND 20
ORDER BY HOUR;

-- ORACLE => TO_CHAR
SELECT 
    TO_CHAR(DATETIME, 'HH24') AS HOUR, 
    COUNT(*) AS COUNT
FROM ANIMAL_OUTS
WHERE TO_CHAR(DATETIME, 'HH24') BETWEEN 9 AND 19
GROUP BY TO_CHAR(DATETIME, 'HH24')
ORDER BY HOUR;

